# Generated by Django 2.2 on 2021-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bright_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
